/*
 * Catalog Reader
 * The students solution to identifying prices on a furniture catalog
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.aixtra.couchcode.server.challenge.model;

import java.util.Objects;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.*;

import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Solution
 */
@JsonPropertyOrder({
  Solution.JSON_PROPERTY_PRODUCT,
  Solution.JSON_PROPERTY_HINTS
})
@JsonTypeName("Solution")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautServerCodegen", date="2022-10-22T16:30:57.436439+02:00[Europe/Berlin]")
@Introspected
public class Solution {
    public static final String JSON_PROPERTY_PRODUCT = "product";
    private Product product;

    public static final String JSON_PROPERTY_HINTS = "hints";
    private List<Hint> hints = null;

    public Solution() {
    }

    public Solution product(Product product) {
        this.product = product;
        return this;
    }

    /**
     * Get product
     * @return product
     **/
    @Valid
    @Nullable
    @Schema(name = "product", required = false)
    @JsonProperty(JSON_PROPERTY_PRODUCT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Product getProduct() {
        return product;
    }

    @JsonProperty(JSON_PROPERTY_PRODUCT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProduct(Product product) {
        this.product = product;
    }

    public Solution hints(List<Hint> hints) {
        this.hints = hints;
        return this;
    }

    public Solution addHintsItem(Hint hintsItem) {
        if (this.hints == null) {
            this.hints = new ArrayList<>();
        }
        this.hints.add(hintsItem);
        return this;
    }

    /**
     * Get hints
     * @return hints
     **/
    @Nullable
    @Schema(name = "hints", required = false)
    @JsonProperty(JSON_PROPERTY_HINTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<Hint> getHints() {
        return hints;
    }

    @JsonProperty(JSON_PROPERTY_HINTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setHints(List<Hint> hints) {
        this.hints = hints;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Solution solution = (Solution) o;
        return Objects.equals(this.product, solution.product) &&
            Objects.equals(this.hints, solution.hints);
    }

    @Override
    public int hashCode() {
        return Objects.hash(product, hints);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Solution {\n");
        sb.append("    product: ").append(toIndentedString(product)).append("\n");
        sb.append("    hints: ").append(toIndentedString(hints)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
