apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr
  labels:
    app: ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        date: "{{ .Values.metadata.date }}"
        app: ocr
    spec:
      containers:
        - name: ocr
          image: europe-west3-docker.pkg.dev/creators-contest-2022/team-{{.Values.team}}/ocr:{{.Values.image.tag}}
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "2Gi"
              cpu: "1"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - containerPort: 5000