micronaut:
  application:
    name: codeYourCouch
  server:
    port: 8080
    context-path: "/"

netty:
  default:
    allocator:
      max-order: 3

backend:
  baseUrl: http://creators-contest-2022.itestra.de
  keycloakUrl: http://creators-contest-2022.itestra.de/auth/realms/creators-contest-2022/protocol/openid-connect/token
  client-id: aixtra
  client-secret: e88b73df-df66-4196-8860-43d5f4f27d2d

  jackson:
    serialization:
      writeEnumsUsingToString: true
      writeDatesAsTimestamps: false
    deserialization:
      readEnumsUsingToString: true
      failOnUnknownProperties: false
      failOnInvalidSubtype: false
