/*
 * Client API
 * API called by backend
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.aixtra.couchcode.client.challenge.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;

import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * EvaluationScore
 */
@JsonPropertyOrder({
  EvaluationScore.JSON_PROPERTY_ACHIEVED_SCORE,
  EvaluationScore.JSON_PROPERTY_POSSIBLE_SCORE
})
@JsonTypeName("EvaluationScore")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-10-22T18:01:35.219427+02:00[Europe/Berlin]")
@Introspected
public class EvaluationScore {
    public static final String JSON_PROPERTY_ACHIEVED_SCORE = "achievedScore";
    private Double achievedScore;

    public static final String JSON_PROPERTY_POSSIBLE_SCORE = "possibleScore";
    private Double possibleScore;

    public EvaluationScore(Double achievedScore, Double possibleScore) {
        this.achievedScore = achievedScore;
        this.possibleScore = possibleScore;
    }

    public EvaluationScore achievedScore(Double achievedScore) {
        this.achievedScore = achievedScore;
        return this;
    }

    /**
     * Get achievedScore
     * @return achievedScore
     **/
    @NotNull
    @JsonProperty(JSON_PROPERTY_ACHIEVED_SCORE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Double getAchievedScore() {
        return achievedScore;
    }

    @JsonProperty(JSON_PROPERTY_ACHIEVED_SCORE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setAchievedScore(Double achievedScore) {
        this.achievedScore = achievedScore;
    }

    public EvaluationScore possibleScore(Double possibleScore) {
        this.possibleScore = possibleScore;
        return this;
    }

    /**
     * Get possibleScore
     * @return possibleScore
     **/
    @NotNull
    @JsonProperty(JSON_PROPERTY_POSSIBLE_SCORE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Double getPossibleScore() {
        return possibleScore;
    }

    @JsonProperty(JSON_PROPERTY_POSSIBLE_SCORE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setPossibleScore(Double possibleScore) {
        this.possibleScore = possibleScore;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EvaluationScore evaluationScore = (EvaluationScore) o;
        return Objects.equals(this.achievedScore, evaluationScore.achievedScore) &&
            Objects.equals(this.possibleScore, evaluationScore.possibleScore);
    }

    @Override
    public int hashCode() {
        return Objects.hash(achievedScore, possibleScore);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EvaluationScore {\n");
        sb.append("    achievedScore: ").append(toIndentedString(achievedScore)).append("\n");
        sb.append("    possibleScore: ").append(toIndentedString(possibleScore)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
